// ISO 3166-1 alpha-2 country code -> ISO 4217 currency code, for the
// countries visitors most commonly arrive from. Deliberately not exhaustive
// (195 countries) — anything missing here just falls back to the platform's
// default currency in lib/currency.js's detection logic, which is a
// perfectly reasonable outcome, not a bug to chase down.
export const COUNTRY_CURRENCY_MAP = {
  IN: "INR",
  US: "USD",
  GB: "GBP",
  CA: "CAD",
  AU: "AUD",
  SG: "SGD",
  AE: "AED",
  NZ: "NZD",
  CH: "CHF",
  JP: "JPY",
  CN: "CNY",
  HK: "HKD",
  ZA: "ZAR",
  BR: "BRL",
  MX: "MXN",
  RU: "RUB",
  SA: "SAR",
  QA: "QAR",
  KW: "KWD",
  BH: "BHD",
  OM: "OMR",
  PK: "PKR",
  BD: "BDT",
  LK: "LKR",
  NP: "NPR",
  MY: "MYR",
  TH: "THB",
  ID: "IDR",
  PH: "PHP",
  VN: "VND",
  KR: "KRW",
  IL: "ILS",
  TR: "TRY",
  EG: "EGP",
  NG: "NGN",
  KE: "KES",
  // Eurozone
  AT: "EUR",
  BE: "EUR",
  CY: "EUR",
  DE: "EUR",
  EE: "EUR",
  ES: "EUR",
  FI: "EUR",
  FR: "EUR",
  GR: "EUR",
  IE: "EUR",
  IT: "EUR",
  LT: "EUR",
  LU: "EUR",
  LV: "EUR",
  MT: "EUR",
  NL: "EUR",
  PT: "EUR",
  SI: "EUR",
  SK: "EUR",
  // Non-euro Europe
  SE: "SEK",
  NO: "NOK",
  DK: "DKK",
  PL: "PLN",
  CZ: "CZK",
  HU: "HUF",
  RO: "RON",
};

export function currencyForCountry(countryCode) {
  return COUNTRY_CURRENCY_MAP[countryCode] || null;
}
